name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: build linux binary
        uses: ./.github/actions/build-go
        id: build-go
