name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: golang:1.14
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: build linux binary
        run: |
          cd lib/cloud_sql_proxy
          . build-linux
